# Generated by Django 3.1.7 on 2021-04-22 09:52

from django.db import migrations, models
import django.db.models.deletion
import localflavor.in_.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon_Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('phone', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('alt_phone', phone_field.models.PhoneField(max_length=31)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', localflavor.in_.models.INStateField(blank=True, max_length=2, null=True)),
                ('pincode', models.PositiveIntegerField(default=0)),
                ('seller_product', models.CharField(max_length=200)),
                ('seller_code', models.IntegerField(default=0)),
                ('seller_product_id', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('get_notified', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, editable=False, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amazon_Seller_Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('product_delivery', models.BooleanField(default=False)),
                ('delivery_date', models.DateTimeField(auto_now=True)),
                ('seller_product', models.CharField(max_length=100)),
                ('seller_offers', models.CharField(default=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('amazon_seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_seller.amazon_seller')),
            ],
        ),
    ]
