# Generated by Django 3.1.7 on 2021-04-20 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon_Seller_Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('product_delivery', models.BooleanField()),
                ('delivery_date', models.DateField()),
                ('seller_product', models.CharField(max_length=100)),
                ('seller_offers', models.CharField(default=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('amazon_seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_seller.amazon_seller')),
            ],
        ),
    ]
