# Generated by Django 3.1.7 on 2021-04-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0002_amazon_seller_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazon_seller',
            old_name='seller_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='amazon_seller',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
