# Generated by Django 3.1.7 on 2021-04-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0002_amazon_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_seller',
            name='id_proof',
            field=models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('Pan Card', 'Pan Card')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amazon_seller',
            name='id_proof_file',
            field=models.FileField(default=1, upload_to='media/Amazon_Sellers/id_proof_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amazon_seller',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/Amazon_Sellers/qr_codes'),
        ),
    ]
