# Generated by Django 3.1.7 on 2021-05-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0003_auto_20210422_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_seller',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
