# Generated by Django 3.1.7 on 2021-04-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0003_auto_20210421_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_seller_notifications',
            name='product_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
