# Generated by Django 3.1.7 on 2021-04-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0004_auto_20210421_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_seller_notifications',
            name='delivery_date',
            field=models.DateField(auto_now=True),
        ),
    ]
