# Generated by Django 3.1.7 on 2021-05-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0004_amazon_seller_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon_seller',
            name='seller_code',
        ),
        migrations.RemoveField(
            model_name='amazon_seller',
            name='seller_product',
        ),
        migrations.RemoveField(
            model_name='amazon_seller',
            name='seller_product_id',
        ),
    ]
