# Generated by Django 3.1.7 on 2021-05-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0005_auto_20210502_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon_seller_notifications',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='amazon_seller_notifications',
            name='product_delivery',
        ),
        migrations.RemoveField(
            model_name='amazon_seller_notifications',
            name='seller_offers',
        ),
        migrations.RemoveField(
            model_name='amazon_seller_notifications',
            name='seller_product',
        ),
    ]
