# Generated by Django 3.1.7 on 2021-05-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0006_auto_20210502_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon_seller_notifications',
            name='email',
        ),
    ]
