# Generated by Django 3.1.7 on 2021-04-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_proprietor', '0002_amazon_proprietor_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_proprietor',
            name='profile',
            field=models.ImageField(blank=True, upload_to='media/Amazon_Proprietor/profile'),
        ),
    ]
