# Generated by Django 3.1.7 on 2021-04-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_proprietor', '0003_amazon_proprietor_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon_proprietor_notifications',
            name='email',
        ),
    ]
