# Generated by Django 3.1.7 on 2021-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_admin', '0002_amazon_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_admin',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
