# Generated by Django 3.1.7 on 2021-04-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_admin', '0003_auto_20210413_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_admin',
            name='profile_photo',
            field=models.ImageField(upload_to='media/Amazon_Admins/profile_photo'),
        ),
    ]
