# Generated by Django 3.1.7 on 2021-04-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_admin', '0004_auto_20210410_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_admin',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
