# Generated by Django 3.1.7 on 2021-05-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amazon_seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile_technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Amazon_Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=100)),
                ('amazon_seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_seller.amazon_seller')),
                ('mobile_technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_mobile.mobile_technology')),
            ],
            options={
                'unique_together': {('mobile_technology',)},
            },
        ),
    ]
