# Generated by Django 3.1.7 on 2021-05-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amazon_seller', '0001_initial'),
        ('amazon_mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_mobile',
            name='amazon_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_seller.amazon_seller'),
        ),
        migrations.AddField(
            model_name='amazon_mobile',
            name='mobile_technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_mobile.mobile_technology'),
        ),
    ]
