# Generated by Django 3.1.7 on 2021-05-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_mobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile_technology',
            old_name='technology',
            new_name='technology_name',
        ),
    ]
