# Generated by Django 3.1.7 on 2021-05-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_mobile', '0002_amazon_mobile_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amazon_Mobile_Notifications',
        ),
    ]
