# Generated by Django 3.1.7 on 2021-05-15 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_mobile', '0002_auto_20210515_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile_technology',
            name='amazon_mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_mobile.amazon_mobile'),
        ),
        migrations.AlterUniqueTogether(
            name='amazon_mobile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='mobile_technology',
        ),
    ]
