# Generated by Django 3.1.7 on 2021-05-02 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0003_auto_20210422_1603'),
        ('amazon_mobile', '0003_delete_amazon_mobile_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile_technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technolgy', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='battery_type',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='body_build',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='body_dimensions',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='body_sim',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='body_weight',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='comm_nfc',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='comm_radio',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='comm_usb',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='comms_bluetooth',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='comms_gps',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='comms_wlan',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='display_resolution',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='display_size',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='features_sensors',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='launch_status',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='main_camera_dual',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='main_camera_features',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='main_camera_video',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='memory_card_slot',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='memory_internal',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='misc_colors',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='misc_models',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='misc_price',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='misc_price_currency',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='mise_sar',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='network_technology',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='platform_chipset',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='platform_cpu',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='platform_gpu',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='platform_os',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='selfie_camera_single',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='selfie_camera_video',
        ),
        migrations.RemoveField(
            model_name='amazon_mobile',
            name='tests_performance',
        ),
        migrations.AddField(
            model_name='amazon_mobile',
            name='amazon_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_seller.amazon_seller'),
        ),
    ]
