# Generated by Django 3.1.7 on 2021-05-16 11:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_mobile', '0003_amazon_mobile_mobile_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_mobile',
            name='mobile_technology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, size=20),
        ),
    ]
