# Generated by Django 3.1.7 on 2021-05-16 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_mobile', '0004_auto_20210516_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_mobile',
            name='mobile_technology',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8),
        ),
    ]
