# Generated by Django 3.1.7 on 2021-05-16 13:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_mobile', '0005_auto_20210516_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_mobile',
            name='mobile_technology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
