# Generated by Django 3.1.7 on 2021-04-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_delivery_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazon_delivery_service',
            old_name='DOB',
            new_name='establish_date',
        ),
        migrations.RenameField(
            model_name='amazon_delivery_service',
            old_name='first_name',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='amazon_delivery_service',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='amazon_delivery_service',
            name='delivery_id',
        ),
        migrations.RemoveField(
            model_name='amazon_delivery_service',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='amazon_delivery_service',
            name='id_proof_file',
        ),
        migrations.RemoveField(
            model_name='amazon_delivery_service',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='amazon_delivery_service',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='amazon_delivery_service',
            name='order_detail_id',
        ),
        migrations.RemoveField(
            model_name='amazon_delivery_service',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='amazon_delivery_service',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='amazon_delivery_service',
            name='supplier_id',
        ),
        migrations.AddField(
            model_name='amazon_delivery_service',
            name='certificate',
            field=models.FileField(default='1.py', upload_to='media/Amazon_Delivery_Service/certificate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amazon_delivery_service',
            name='profile_photo',
            field=models.ImageField(upload_to='media/Amazon_Delivery_Service/profile'),
        ),
        migrations.CreateModel(
            name='Amazon_Delivery_Service_Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('amazon_delivery_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_delivery_service.amazon_delivery_service')),
            ],
        ),
    ]
