# Generated by Django 3.1.7 on 2021-04-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_delivery_service', '0002_auto_20210422_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazon_delivery_boy',
            old_name='amazon_deliery_service',
            new_name='amazon_delivery_service',
        ),
    ]
