# Generated by Django 3.1.7 on 2021-04-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_delivery_service', '0002_auto_20210412_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_delivery_service',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/Amazon_Delivery_Service/qr_codes'),
        ),
    ]
