# Generated by Django 3.1.7 on 2021-04-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_delivery_service', '0003_auto_20210412_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon_delivery_service',
            name='gender',
        ),
    ]
