# Generated by Django 3.1.7 on 2021-04-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_delivery_service', '0003_auto_20210427_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazon_delivery_boy',
            old_name='amazon_delivery_service',
            new_name='amazon_delivry_service',
        ),
    ]
