# Generated by Django 3.1.7 on 2021-04-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_delivery_service', '0007_auto_20210413_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_delivery_boy',
            name='amazon_deliery_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amazon_delivery_service.amazon_delivery_service'),
            preserve_default=False,
        ),
    ]
