# Generated by Django 3.1.7 on 2021-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_amazon_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon_customer',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='amazon_customer',
            name='id_proof_file',
        ),
        migrations.RemoveField(
            model_name='amazon_customer',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='amazon_customer',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='amazon_customer',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
    ]
