# Generated by Django 3.1.7 on 2021-04-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_amazon_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_customer',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='amazon_customer',
            name='middle_name',
            field=models.CharField(max_length=200),
        ),
    ]
