# Generated by Django 3.1.7 on 2021-04-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_employee',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/Employee_Admins/qr_codes'),
        ),
    ]
