# Generated by Django 3.1.7 on 2021-05-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_employee', '0002_amazon_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_employee',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True, unique=True),
        ),
    ]
