# Generated by Django 3.1.7 on 2021-05-12 14:05

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_employee', '0003_auto_20210507_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_employee',
            name='sallery',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='INR', max_digits=13, null=True),
        ),
    ]
