# Generated by Django 3.1.7 on 2021-04-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_employee', '0003_auto_20210410_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_employee',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/Employee_Admins/qr_codes'),
        ),
        migrations.AlterField(
            model_name='amazon_employee',
            name='id_proof_file',
            field=models.FileField(upload_to='media/Amazon_Employee/id_proof_file'),
        ),
        migrations.AlterField(
            model_name='amazon_employee',
            name='profile_photo',
            field=models.ImageField(upload_to='media/Amazon_Employee/profile'),
        ),
    ]
