# Generated by Django 3.1.7 on 2021-04-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_employee', '0004_auto_20210410_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_employee',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
