# Generated by Django 3.1.7 on 2021-04-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_employee', '0005_auto_20210410_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_employee',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/Amazon_Employee/qr_codes'),
        ),
    ]
