# Generated by Django 3.1.7 on 2021-04-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_employee', '0006_auto_20210410_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_employee',
            name='Past_Experince',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='amazon_employee',
            name='Resume',
            field=models.FileField(default='', upload_to='media/Amazon_Employee/resume_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amazon_employee',
            name='sallery',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
    ]
