# Generated by Django 3.1.7 on 2021-04-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_employee', '0008_auto_20210411_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazon_employee_notifications',
            old_name='amazon_admin',
            new_name='amazon_employee',
        ),
    ]
