# Generated by Django 3.1.7 on 2021-04-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_employee', '0009_auto_20210411_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon_employee_notifications',
            name='email',
        ),
    ]
