# Generated by Django 3.1.7 on 2021-04-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_amazon_proprietor',
            field=models.BooleanField(default=False),
        ),
    ]
